/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminMitarbeiterRouteImport } from './routes/_authenticated/admin.mitarbeiter'
import { Route as AuthenticatedAdminProjekteRouteImport } from './routes/_authenticated/admin.projekte'
import { Route as AuthenticatedAdminTelefonnummernRouteImport } from './routes/_authenticated/admin.telefonnummern'
import { Route as AuthenticatedAdminTelegramRouteImport } from './routes/_authenticated/admin.telegram'
import { Route as AuthenticatedAdminVicsRouteImport } from './routes/_authenticated/admin.vics'
import { Route as AuthenticatedMitarbeiterIndexRouteImport } from './routes/_authenticated/mitarbeiter.index'
import { Route as AuthenticatedMitarbeiterOnboardingRouteImport } from './routes/_authenticated/mitarbeiter.onboarding'
import { Route as AuthenticatedMitarbeiterAuftraegeIndexRouteImport } from './routes/_authenticated/mitarbeiter.auftraege.index'
import { Route as AuthenticatedMitarbeiterAuftraegeVicIdRouteImport } from './routes/_authenticated/mitarbeiter.auftraege.$vicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMitarbeiterRoute =
  AuthenticatedAdminMitarbeiterRouteImport.update({
    id: '/admin/mitarbeiter',
    path: '/admin/mitarbeiter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjekteRoute =
  AuthenticatedAdminProjekteRouteImport.update({
    id: '/admin/projekte',
    path: '/admin/projekte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTelefonnummernRoute =
  AuthenticatedAdminTelefonnummernRouteImport.update({
    id: '/admin/telefonnummern',
    path: '/admin/telefonnummern',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTelegramRoute =
  AuthenticatedAdminTelegramRouteImport.update({
    id: '/admin/telegram',
    path: '/admin/telegram',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVicsRoute = AuthenticatedAdminVicsRouteImport.update({
  id: '/admin/vics',
  path: '/admin/vics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMitarbeiterIndexRoute =
  AuthenticatedMitarbeiterIndexRouteImport.update({
    id: '/mitarbeiter/',
    path: '/mitarbeiter/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMitarbeiterOnboardingRoute =
  AuthenticatedMitarbeiterOnboardingRouteImport.update({
    id: '/mitarbeiter/onboarding',
    path: '/mitarbeiter/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMitarbeiterAuftraegeIndexRoute =
  AuthenticatedMitarbeiterAuftraegeIndexRouteImport.update({
    id: '/mitarbeiter/auftraege/',
    path: '/mitarbeiter/auftraege/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMitarbeiterAuftraegeVicIdRoute =
  AuthenticatedMitarbeiterAuftraegeVicIdRouteImport.update({
    id: '/mitarbeiter/auftraege/$vicId',
    path: '/mitarbeiter/auftraege/$vicId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/mitarbeiter': typeof AuthenticatedAdminMitarbeiterRoute
  '/admin/projekte': typeof AuthenticatedAdminProjekteRoute
  '/admin/telefonnummern': typeof AuthenticatedAdminTelefonnummernRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/vics': typeof AuthenticatedAdminVicsRoute
  '/mitarbeiter/onboarding': typeof AuthenticatedMitarbeiterOnboardingRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/mitarbeiter/': typeof AuthenticatedMitarbeiterIndexRoute
  '/mitarbeiter/auftraege/$vicId': typeof AuthenticatedMitarbeiterAuftraegeVicIdRoute
  '/mitarbeiter/auftraege/': typeof AuthenticatedMitarbeiterAuftraegeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/mitarbeiter': typeof AuthenticatedAdminMitarbeiterRoute
  '/admin/projekte': typeof AuthenticatedAdminProjekteRoute
  '/admin/telefonnummern': typeof AuthenticatedAdminTelefonnummernRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/vics': typeof AuthenticatedAdminVicsRoute
  '/mitarbeiter/onboarding': typeof AuthenticatedMitarbeiterOnboardingRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/mitarbeiter': typeof AuthenticatedMitarbeiterIndexRoute
  '/mitarbeiter/auftraege/$vicId': typeof AuthenticatedMitarbeiterAuftraegeVicIdRoute
  '/mitarbeiter/auftraege': typeof AuthenticatedMitarbeiterAuftraegeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/mitarbeiter': typeof AuthenticatedAdminMitarbeiterRoute
  '/_authenticated/admin/projekte': typeof AuthenticatedAdminProjekteRoute
  '/_authenticated/admin/telefonnummern': typeof AuthenticatedAdminTelefonnummernRoute
  '/_authenticated/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/_authenticated/admin/vics': typeof AuthenticatedAdminVicsRoute
  '/_authenticated/mitarbeiter/onboarding': typeof AuthenticatedMitarbeiterOnboardingRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/mitarbeiter/': typeof AuthenticatedMitarbeiterIndexRoute
  '/_authenticated/mitarbeiter/auftraege/$vicId': typeof AuthenticatedMitarbeiterAuftraegeVicIdRoute
  '/_authenticated/mitarbeiter/auftraege/': typeof AuthenticatedMitarbeiterAuftraegeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/mitarbeiter'
    | '/admin/projekte'
    | '/admin/telefonnummern'
    | '/admin/telegram'
    | '/admin/vics'
    | '/mitarbeiter/onboarding'
    | '/admin/'
    | '/mitarbeiter/'
    | '/mitarbeiter/auftraege/$vicId'
    | '/mitarbeiter/auftraege/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/mitarbeiter'
    | '/admin/projekte'
    | '/admin/telefonnummern'
    | '/admin/telegram'
    | '/admin/vics'
    | '/mitarbeiter/onboarding'
    | '/admin'
    | '/mitarbeiter'
    | '/mitarbeiter/auftraege/$vicId'
    | '/mitarbeiter/auftraege'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/mitarbeiter'
    | '/_authenticated/admin/projekte'
    | '/_authenticated/admin/telefonnummern'
    | '/_authenticated/admin/telegram'
    | '/_authenticated/admin/vics'
    | '/_authenticated/mitarbeiter/onboarding'
    | '/_authenticated/admin/'
    | '/_authenticated/mitarbeiter/'
    | '/_authenticated/mitarbeiter/auftraege/$vicId'
    | '/_authenticated/mitarbeiter/auftraege/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mitarbeiter': {
      id: '/_authenticated/admin/mitarbeiter'
      path: '/admin/mitarbeiter'
      fullPath: '/admin/mitarbeiter'
      preLoaderRoute: typeof AuthenticatedAdminMitarbeiterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projekte': {
      id: '/_authenticated/admin/projekte'
      path: '/admin/projekte'
      fullPath: '/admin/projekte'
      preLoaderRoute: typeof AuthenticatedAdminProjekteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/telefonnummern': {
      id: '/_authenticated/admin/telefonnummern'
      path: '/admin/telefonnummern'
      fullPath: '/admin/telefonnummern'
      preLoaderRoute: typeof AuthenticatedAdminTelefonnummernRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/telegram': {
      id: '/_authenticated/admin/telegram'
      path: '/admin/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AuthenticatedAdminTelegramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vics': {
      id: '/_authenticated/admin/vics'
      path: '/admin/vics'
      fullPath: '/admin/vics'
      preLoaderRoute: typeof AuthenticatedAdminVicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mitarbeiter/': {
      id: '/_authenticated/mitarbeiter/'
      path: '/mitarbeiter'
      fullPath: '/mitarbeiter/'
      preLoaderRoute: typeof AuthenticatedMitarbeiterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mitarbeiter/onboarding': {
      id: '/_authenticated/mitarbeiter/onboarding'
      path: '/mitarbeiter/onboarding'
      fullPath: '/mitarbeiter/onboarding'
      preLoaderRoute: typeof AuthenticatedMitarbeiterOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mitarbeiter/auftraege/': {
      id: '/_authenticated/mitarbeiter/auftraege/'
      path: '/mitarbeiter/auftraege'
      fullPath: '/mitarbeiter/auftraege/'
      preLoaderRoute: typeof AuthenticatedMitarbeiterAuftraegeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mitarbeiter/auftraege/$vicId': {
      id: '/_authenticated/mitarbeiter/auftraege/$vicId'
      path: '/mitarbeiter/auftraege/$vicId'
      fullPath: '/mitarbeiter/auftraege/$vicId'
      preLoaderRoute: typeof AuthenticatedMitarbeiterAuftraegeVicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminMitarbeiterRoute: typeof AuthenticatedAdminMitarbeiterRoute
  AuthenticatedAdminProjekteRoute: typeof AuthenticatedAdminProjekteRoute
  AuthenticatedAdminTelefonnummernRoute: typeof AuthenticatedAdminTelefonnummernRoute
  AuthenticatedAdminTelegramRoute: typeof AuthenticatedAdminTelegramRoute
  AuthenticatedAdminVicsRoute: typeof AuthenticatedAdminVicsRoute
  AuthenticatedMitarbeiterOnboardingRoute: typeof AuthenticatedMitarbeiterOnboardingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedMitarbeiterIndexRoute: typeof AuthenticatedMitarbeiterIndexRoute
  AuthenticatedMitarbeiterAuftraegeVicIdRoute: typeof AuthenticatedMitarbeiterAuftraegeVicIdRoute
  AuthenticatedMitarbeiterAuftraegeIndexRoute: typeof AuthenticatedMitarbeiterAuftraegeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminMitarbeiterRoute: AuthenticatedAdminMitarbeiterRoute,
  AuthenticatedAdminProjekteRoute: AuthenticatedAdminProjekteRoute,
  AuthenticatedAdminTelefonnummernRoute: AuthenticatedAdminTelefonnummernRoute,
  AuthenticatedAdminTelegramRoute: AuthenticatedAdminTelegramRoute,
  AuthenticatedAdminVicsRoute: AuthenticatedAdminVicsRoute,
  AuthenticatedMitarbeiterOnboardingRoute:
    AuthenticatedMitarbeiterOnboardingRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedMitarbeiterIndexRoute: AuthenticatedMitarbeiterIndexRoute,
  AuthenticatedMitarbeiterAuftraegeVicIdRoute:
    AuthenticatedMitarbeiterAuftraegeVicIdRoute,
  AuthenticatedMitarbeiterAuftraegeIndexRoute:
    AuthenticatedMitarbeiterAuftraegeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
