// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hppylojeoutwymkrqkek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwcHlsb2plb3V0d3lta3Jxa2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk1NjAyMjIsImV4cCI6MjEwNTEzNjIyMn0.3Qd2rdYJQT6jzIsF1ap-0dtYaK2uxMIHfP9jXKgreYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});